# Generated by Django 5.1.1 on 2024-12-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='surname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='form',
            name='email',
        ),
    ]
